### ISSUE TITLE
Publish for Scala 2.12

### ISSUE THREAD

**Issue by Sciss** [dwalend/Disentangle#15]
Hi! I'm interested in your library, but there is no published artifact for Scala 2.12.x; would you mind publishing the last stable version using current Scala? Thanks!

**Comment by dwalend** [comment]
Will do. I'll find some idle time before Thursday.

They deprecated Stack (Why? Turning loved stacks) but I think I'll stay loyal to it anyway.

**Comment by Sciss** [comment]
It says

> Stack is an inelegant and potentially poorly-performing wrapper around List. Use List instead: stack push x becomes x :: list; stack.pop is list.tail.

Anyway, it's not removed, so no need to change anything for Scala 2.12.

**Comment by dwalend** [comment]
I'm able to download v 0.2.2 in a build file now (from https://repo1.maven.org/maven2/net/walend/disentangle/graph_2.12/0.2.2/graph_2.12-0.2.2.jar )

It hasn't appeared on https://mvnrepository.com/artifact/net.walend.disentangle/graph yet.

I'll push the code changes tonight after work. (I had to do some hackery in the build.sbt that includes a password. Probably an out-of-date plugin in the works.)

**Comment by Sciss** [comment]
Thanks, the artifacts are visible here: http://search.maven.org/#search%7Cga%7C1%7Cdisentangle
